name: Manually publish NuGet Package
run-name: Publish NuGet from ${{ github.ref_name }}

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: Logos-Payment-Solution/AiO-Workflows/.github/workflows/manual-nuget-publish.yml@v1
    secrets: inherit
